site_name: Pyr0-Piezo
site_description: Documentation for the Pyr0-Piezo Z-probe sensor
site_author: Alan "pyr0ball" Weinstock
repo_url: https://github.com/pyr0ball/pyr0piezo/

markdown_extensions:
  #http://pythonhosted.org/Markdown/extensions/admonition.html
  - admonition:
  - toc:
      permalink: True

nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'FAQ': 'faq.md'
  - 'Installation': 'installation.md'
    - 'Core XY': 'mounts/core-xy'
      - 'Hypercube Evo (On Head)': 'mounts/core-xy/hevo-on-head'
    - 'Creality Family': 'mounts/creality'
      - 'CR-10 Family': 'mounts/creality/creality-original-head'
      - 'Ender 3 Family': 'mounts/creality/creality-original-head'
    - 'Delta': 'mounts/delta/'
      - 'On Head': 'mounts/delta/delta-head.md'
      - 'Under Bed': 'mounts/delta/delta-under-bed.md'
    - 'Deltesian': 'mounts/deltesian/deltesian.md'
    - 'Mendel': 'mounts/mendel/'
      - 'On Head': 'mounts/mendel/mendel-on-head.md'
      - 'Gantry Mount': 'mounts/mendel/mendel-gantry-mount.md'
    - 'Prusa Mendel': 'mounts/prusa-mendel'
      - 'Prusa i3 on Head': 'mounts/prusa-mendel/i3-on-head.md'
      - 'HICTOP i3': 'mounts/hictop-i3.md'
    - 'Ultimaker Kinematics': 'mounts/ultimaker'
      - 'Makerbot Original Under Bed': 'mounts/ultimaker/makerbot-under-bed.md'
      - 'Ultimaker Under Bed': 'mounts/ultimaker/um-under-bed.md'
  - 'Configuration': 'config.md'
  - 'Main Site': 'https://pyroballpcbs.com'

google_analytics: ['UA-135668867-1', 'pyroballpcbs.com']
