site_name: Pyr0-Piezo
site_description: Documentation for the Pyr0-Piezo Z-probe sensor
site_author: Alan "pyr0ball" Weinstock
repo_url: https://github.com/pyr0ball/pyr0piezo/

theme:
  name: 'material'
  logo: 'docs/assets/images/Pyr0ball-logo.png'
  #custom_dir: 'mkdocs-theme-overrides'

markdown_extensions:
  #http://pythonhosted.org/Markdown/extensions/admonition.html
  - admonition:
  - toc:
      permalink: True

nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'FAQ': 'faq.md'
  - 'Installation':
    - 'Start Here': 'installation.md'
    - 'Printer Specific':
      - 'Core XY':
        - 'Hypercube Evo (On Head)': 'mounts/core-xy/hevo-on-head.md'
      - 'Creality Family':
        - 'CR-10 Family': 'mounts/creality/creality-original-head.md'
        - 'Ender 3 Family': 'mounts/creality/creality-original-head.md'
      - 'Delta':
        - 'Monoprice Delta Mini': 'mounts/delta/monoprice-delta-mini.md'
        - 'On Head': 'mounts/delta/delta-head.md'
        - 'Under Bed': 'mounts/delta/delta-under-bed.md'
      - 'Deltesian': 'mounts/deltesian/deltesian.md'
      - 'Mendel':
        - 'On Head': 'mounts/mendel/mendel-on-head.md'
        - 'Gantry Mount': 'mounts/mendel/mendel-gantry-mount.md'
      - 'Prusa Mendel':
        - 'Prusa i3 on Head': 'mounts/prusa-mendel/i3-on-head.md'
        - 'HICTOP i3': 'mounts/prusa-mendel/hictop-i3.md'
      - 'Quadrap':
        - 'Makerbot Original Under Bed': 'mounts/quadrap/makerbot-under-bed.md'
        - 'Ultimaker Under Bed': 'mounts/quadrap/um-under-bed.md'
  - 'Configuration':
    - 'Start Here': 'config.md'
    - 'Firmware Config':
      - 'Marlin': 'tutorials/config/printer-firmware/marlin/marlin-config.md'
      - 'Klipper': 'tutorials/config/printer-firmware/klipper/klipper-config.md'
  - 'Main Site': 'https://pyroballpcbs.com'

google_analytics: ['UA-135668867-1', 'pyroballpcbs.com']
